- name: Configure ETCD
  become: true
  block:
    - name: Check if ETCD is already installed
      shell: which etcd && which etcdctl
      register: etcd_check
      when: "'tag_Role_master_node' in group_names"
      ignore_errors: yes
    
    # - name: print result
    #   debug:
    #     var: etcd_check
    #   when: "'tag_Role_master_node' in group_names"

    - name: Download and install etcd and etcdctl
      ansible.builtin.shell: |
        source /etc/profile.d/env_vars.sh && wget -q \
        "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz" \
        -O /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz
        
        source /etc/profile.d/env_vars.sh && tar -xvf /tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz -C /tmp/

        source /etc/profile.d/env_vars.sh && sudo mv /tmp/etcd-{{ etcd_version }}-linux-amd64/etcd* /usr/local/bin/
      when: 
        - "'tag_Role_master_node' in group_names"
        - etcd_check.rc != 0

    - name: create symlinks for etcd
      ansible.builtin.shell: |
        if [ ! -L "/etc/etcd/ca.crt" ]; then
          sudo ln -s /var/lib/kubernetes/pki/ca.crt /etc/etcd/ca.crt
        fi

        if [ ! -L "/etc/etcd/etcd-server.crt" ]; then
          sudo ln -s /var/lib/kubernetes/pki/etcd-server.crt /etc/etcd/etcd-server.crt
        fi

        if [ ! -L "/etc/etcd/etcd-server.key" ]; then
          sudo ln -s /var/lib/kubernetes/pki/etcd-server.key /etc/etcd/etcd-server.key
        fi
      when: "'tag_Role_master_node' in group_names"
      notify: Enable and restart etcd