---
- name: Add templates to master-nodes
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  when: "'tag_Role_master_node' in group_names"
  loop: "{{ component_templates }}"
  become: true

- name: fill templates with env vars in master-nodes
  ansible.builtin.shell: |
    source /etc/profile.d/env_vars.sh && envsubst < "{{ item.dest }}" > /root/output
    mv /root/output "{{ item.dest }}"
  loop: "{{ component_templates }}"
  when: "'tag_Role_master_node' in group_names"
  become: true

- name: enable and start services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: true
  loop: "{{ components }}"
  when: "'tag_Role_master_node' in group_names"
  become: true