---
# tasks file for setup_falcon

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Download the Falcon Script
  ansible.builtin.get_url:
    url: "{{ falcon_agent_script_url }}"
    dest: "{{ falcon_agent_script_location }}"
    mode: '0755'
  when: "'falcon-sensor.service' not in services"
  
- name: Execute install_falcon script
  command: "sudo bash {{ falcon_agent_script_location }}"
  when: "'falcon-sensor.service' not in services"

- name: Ensure the service is running and enabled on startup
  ansible.builtin.service:
    name: falcon-sensor
    state: restarted
    enabled: yes
  become: true
