- name: Common tasks for cluster nodes
  become: true
  block:
    - name: install common packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ common_packages }}"
    
    - name: Check if net.ipv4.ip_forward is enabled
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
      register: ipv4_forward_status
    
    - name: Enable net.ipv4.ip_forward
      ansible.builtin.lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: net.ipv4.ip_forward = 1
        create: yes
      when: ipv4_forward_status.changed

    - name: Reload sysctl settings
      shell: sudo sysctl --system
      when: ipv4_forward_status.changed
    
- include_tasks: common/containerd.yml

- include_tasks: common/runc.yml

- include_tasks: common/cni.yml

- include_tasks: common/components.yml