- name: generate join token
  become: true
  block:
    - name: Ensure API server is reachable
      command: curl -k https://localhost:6443/version
      register: api_check
      until: api_check.rc == 0
      retries: 5
      delay: 20
      when: "'tag_Role_master' in group_names"

    - name: Generate kubeadm join command
      shell: kubeadm token create --print-join-command
      register: kubeadm_token
      when: "'tag_Role_master' in group_names"

- name: Join worker nodes to cluster
  become: true
  command: "{{ hostvars[groups['tag_Role_master'][0]]['kubeadm_token'].stdout }}"
  ignore_errors: true
  when: "'tag_Role_worker' in group_names"
  register: kubeadm_join_output

- name: print kubeadm_join output
  debug:
    var: kubeadm_join_output.stdout_lines
  when: "'tag_Role_worker' in group_names"