---
# vars file for roles/k8s_cluster_kubeadm
common_packages:
  - curl
  - device-mapper-persistent-data
  - iproute-tc
  - iptables
  - lvm2
  - nc
  - python3-dnf-plugin-versionlock
  - telnet
  - vim
  - yum-utils

system_modules:
  - overlay
  - br_netfilter
  - ip_tables
  - iptable_filter

components:
  - kubeadm
  - kubectl
  - kubelet