---
# playbook to call launch_ec2 role
- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: roles/launch_ec2
  tags: provisioning

- name: Set Hostname on Newly Created Instances
  hosts: new_instances
  become: true
  tasks:
    - name: Set system hostname to the 'Name' tag value
      hostname:
        name: "{{ inventory_hostname }}"

- name: Install Falcon agent
  hosts: new_instances
  gather_facts: true
  roles:
    - role: roles/setup_falcon
  tags: falcon