- name: setup cni plugins
  become: true
  block:
    - name: ensure /opt/cni/bin directory exists
      file:
        path: /opt/cni/bin
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: check if cni plugins are installed
      command: which macvlan
      register: cni_installed
      ignore_errors: yes

    - name: Download & Extract cni_plugins tar.gz
      unarchive:
        src: "{{ cni_url_path }}/{{ cni_version_path }}"
        dest: /opt/cni/bin
        owner: root
        group: root
        mode: 0755
        remote_src: yes
      register: unarchive_result
      when: cni_installed.rc != 0