- name: configure Forwarding IPv4 and letting iptables see bridged traffic
  become: true
  block:
    - name: check if kernel module-k8s.conf file is present
      stat:
        path: /etc/modules-load.d/k8s.conf
      register: module_file

    - name: add kernel module-k8s.conf file
      copy:
        src: "files/module-k8s.conf"
        dest: "/etc/modules-load.d/k8s.conf"
      when: not module_file.stat.exists

    - name: enable modules
      community.general.modprobe:
        name: "{{ item}}"
        state: present
      loop: "{{ system_modules }}"
    
    - name: check if sysctl-k8s.conf file is present
      stat:
        path: /etc/sysctl.d/k8s.conf
      register: sysctl_file
    
    - name: add sysctl-k8s.conf file
      copy:
        src: "files/sysctl-k8s.conf"
        dest: "/etc/sysctl.d/k8s.conf"
      when: not sysctl_file.stat.exists

    - name: Load sysctl settings
      shell: sysctl --system